---
title: "SNSF Budget"
output: 
  flexdashboard::flex_dashboard:
    theme: cerulean
    social: menu
    source_code: https://git.io/vb2Tv
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
if (!require(pacman)) install.packages("pacman")
if (!require(janitor)) install.packages("janitor")
p_load(
  "flexdashboard", 
  "networkD3",
  "tidyverse", 
  "lubridate", 
  "stringr", 
  "magrittr", 
  "rio")
YEAR <- 2019
```

Column
-------------------------------------

### Approved Amounts for SNSF Grants Starting in `r YEAR`

```{r}
time_range <- ymd(c(str_c(YEAR, "-01-01"), str_c(YEAR, "-12-31")))

## 
grants <- read.csv2(
  url("http://p3.snf.ch/P3Export/P3_GrantExport.csv"),
  stringsAsFactors = FALSE) %>% 
  janitor::clean_names()

## easier to maintain if download and wrangle separately
grants <- grants %>%
  select(funding_instrument_hierarchy,
         discipline_number,
         university,
         approved_amount, 
         start_date) %>%
  mutate(start_date = dmy(start_date)) %>% 
  filter(between(start_date, time_range[1], time_range[2])) %>% 
  select(-start_date) %>% 
  mutate( # clean intrument names
    instrument = str_replace(funding_instrument_hierarchy, "^$", "Miscellaneous"),
    instrument = str_replace(instrument, "(.*)[Ff]ellowships", "Fellowships"),
    instrument = str_replace(instrument, "(.*)NRPs(.*)", "NRPs"),
    instrument = str_replace(instrument, "(.*)r4d(.*)", "r4d"),
    instrument = str_c(instrument, " ")) %>%
  mutate( # clean institution names
    institution = str_replace(university, "^$", "Other"),
    institution = str_replace(institution, "(.*)[[:space:]][-][[:space:]]", ""),
    institution = str_replace(institution, "IACH", "International"),
    institution = str_c(institution, " ")) %>%
  filter(!str_detect(approved_amount, "not included")) %>%
  mutate(
    approved_amount = as.numeric(approved_amount),
    domain = str_sub(discipline_number, 1, 1)) %>%
  mutate(
    domain = str_replace(domain, "1", "SSH "),
    domain = str_replace(domain, "2", "STEM "),
    domain = str_replace(domain, "3", "BIOMED "),
    domain = str_replace(domain, "[04-9]", "NA "),
    domain = str_replace_na(domain, "NA "))


institutions <- count(grants, institution) %>%
  mutate(uni = ifelse(n > 10, institution, "Other "))

grants <- grants %>%
  left_join(institutions, by = "institution") %>%
  select(approved_amount, instrument, uni, domain)

nodes <- tibble(name = grants %$% unique(c(instrument, uni, domain))) %>%
  rowid_to_column("id") %>%
  mutate(id = id - 1) # start at 0

links_left <- grants %>%
  group_by(instrument, uni) %>%
  summarise(value = sum(approved_amount)) %>%
  ungroup() %>%
  left_join(nodes, by = c("instrument" = "name")) %>%
  rename("source" = id) %>%
  left_join(nodes, by = c("uni" = "name")) %>%
  rename("target" = id) %>%
  select(source, target, value)

links_right <- grants %>%
  group_by(uni, domain) %>%
  summarise(value = sum(approved_amount)) %>%
  ungroup() %>%
  left_join(nodes, by = c("uni" = "name")) %>%
  rename("source" = id) %>%
  left_join(nodes, by = c("domain" = "name")) %>%
  rename("target" = id) %>%
  select(source, target, value)

links <- bind_rows(links_left, links_right)
nodes <- nodes %>% select(-id) %>%
  as.data.frame(stringsAsFactors = FALSE)
  
links <- links %>%
  mutate(source = as.integer(source),
         target = as.integer(target)) %>%
  as.data.frame(stringsAsFactors = FALSE)

sankeyNetwork(
  Links = links, Nodes = nodes, 
  Source = "source", Target = "target", Value = "value", NodeID = "name",
  units = "CHF", fontSize = 14, nodeWidth = 45)

```

> Last updated: `r Sys.time()`. Compiled with `r version$version.string`.
